import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./_styles/reset.css";
import "./_styles/globals.css";
import { StoreProvider } from "./_store/StoreProvider";
import { Suspense } from "react";
import Loading from "./_components/common/Loading";
import { Header } from "./_components/common/Header";
import { Footer } from "./_components/common/Footer";
import Gnb, { IGnbProps } from "./_components/common/Gnb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuList: IGnbProps = {
    menuList: [
      { depth1: "대시보드", isOpenDepth1: false },
      {
        depth1: "제품관리",
        depth2: [
          "제품",
          "토핑",
          "하프&하프 관리",
          "도미노콘/상품권 관리",
          "일시중지메뉴",
          "쇼핑몰 상품코드 내역",
          "알레르기 유발성분 관리",
          "난수쿠폰 생성관리",
        ],
        isOpenDepth1: true,
      },
      { depth1: "회원관리", isOpenDepth1: false },
      { depth1: "통계관리", isOpenDepth1: true },
    ],
  };

  return (
    <>
      <StoreProvider>
        <html lang="ko">
          <Suspense fallback={<Loading />}>
            <body className={inter.className}>
              <Header />
              <Gnb {...menuList} />
              <main className="main-wrap">{children}</main>
              <Footer />
            </body>
          </Suspense>
        </html>
      </StoreProvider>
    </>
  );
}
